config/routes.rb
Crunch::Application.routes.draw do |map|
  resource :account
  resource :user_session

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :password_reset

  root :to => 'home#index'

  namespace :admin do
    resources :users
    resource :impersonation
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include User::Role
  self.per_page = 10

  acts_as_authentic do |c|
    c.login_field = 'email'
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

end

app/models/user/role.rb
module User::Role
  ROLES = {:guest => 1, :user => 2, :manager => 4, :admin => 8}.freeze

  ##
  # Array of the user's roles as symbols for use with declarative_authorization
  def role_symbols
    ROLES.inject([]) do |accum, role|
      accum << role[0] if has_role?(role[1])
      accum
    end
  end

  ##
  # Bitwise comparison of role_mask with the supplied role. If role is passed in as a symbol or a string the integer
  # value is looked up in the ROLES hash
  def has_role?(role_sym)
    lookup_role_value(role_sym) & role_mask > 0
  end

  ##
  # Adds a role to a user. Accepts the same input as has_role?
  def add_role(role_sym)
    self.role_mask += lookup_role_value(role_sym)
    self
  end

  ##
  # Removes a role to a user. Accepts the same input as has_role?
  def remove_role(role_sym)
    self.role_mask -= lookup_role_value(role_sym)
    self
  end

  ##
  # Replaces current set of roles w\ ones from array
  def replace_roles(roles)
    self.role_mask = Array(roles).inject(0) {|accum, role| accum += lookup_role_value(role) }
    self
  end

  private
  def lookup_role_value(_role)
    case _role
      when Symbol then ROLES[_role]
      when String then ROLES[_role.to_sym]
      when 0 then raise(ArgumentError, "Role can't be 0")
      when nil then raise(ArgumentError, "Role can't be nil")
      else _role
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  filter_access_to :all, :require => :read

  def index
    @users = User.paginate :page => params[:page], :order => 'updated_at DESC'
  end

  def update
    if user.update_attributes(params[:user])
      flash[:notice] = 'Successfully updated user.'
    else
      flash[:error] = 'Failed to update user.'
    end
    redirect_to admin_users_path
  end

  def destroy
    if user.destroy
      flash[:notice] = 'Successfully deleted user.'
    else
      flash[:error] = 'Failed to delete user.'
    end
    redirect_to admin_users_path
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/views/admin/users/index.html.erb
<% title "Manage Users" %>
<p><%= link_to "New User", new_account_path %></p>
<% if @users.present? %>
  <table>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Roles</th>
      <th>Approved</th>
      <td></td>
      <td></td>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= time_ago_in_words user.created_at %></td>
      <td><%= time_ago_in_words user.updated_at %></td>
      <td><%= user.role_symbols.join(", ") %></td>
      <td>
        <% if user.approved? %>
          Yes
        <% else %>
          <%= form_for user, :url => admin_user_path(user) do |f| %>
            <%= f.hidden_field :approved, :value => true %>
            <%= f.submit "Approve" %>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= form_tag admin_impersonation_path do %>
          <%= hidden_field_tag "user[id]", user.id  %>
          <%= submit_tag "Impersonate" %>
        <% end %>
      </td>
      <td>
        <%= button_to "Delete", admin_user_path(user), :confirm => "Are you sure?", :method => :delete %>
      </td>
    </tr>
    <% end %>
  </table>
  <%= will_paginate @users %>
<% end %>