config/routes.rb
Crunch::Application.routes.draw do |map|
  resource :account
  resource :user_session

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :password_reset

  root :to => 'home#index'

  namespace :admin do
    resources :users
    resource :impersonation
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserNotification.new_account_email(@user).deliver
      flash[:notice] = 'Registration successful.'
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = 'Successfully updated profile.'
      redirect_back_or_default root_url
    else
      render :action => 'edit'
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= f.inputs do %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
<% end %>
<%= f.buttons %>

app/views/accounts/edit.html.erb
<% title "Edit Profile" %>

<%= semantic_form_for @user, :url => account_path(@user) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<p>&nbsp;</p>

<p>
  You currently logged in on <%= @user.current_login_at %> from <%= @user.current_login_ip %><br/>
  <% if @user.last_login_at %>You last logged in on <%= @user.last_login_at %> from <%= @user.last_login_ip %><% end %><br/>
  Your account was created on <%= @user.created_at %><br/>
</p>

app/views/accounts/new.html.erb
<% title "New User" %>

<%= semantic_form_for @user, :url => account_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>